### ISSUE TITLE
Config.txt file issues

### ISSUE THREAD

**Issue by Rolzzz** [RP6conrad/ESP-GPS-Logger#12]
Hello there,

Few things I've noticed in the config file - this might be something to do with in built web browser

"cal_speed" always reverts back to "3.6km/h" instead of staying on pre-set, mine is "1.9438 knots"

most annoying one

ssid only keeps first word of ssid - for example my ssid is "Moonbase Alpha 2.4Ghz" but in web browser config it only shows "Moonbase" so when I change a setting and don't re-set this I lose wifi connectivity and have to try to connect via the default AP

Board and Sail logo links in web browser both point board link https://www.seabreeze.com.au/img/photos/windsurfing/19375156.jpg so choosing Severne Sail presents Simmer logo (number 8)

**Comment by RP6conrad** [comment]
The cal_speed is a bug, will be fixed in the next update.
The SSID is also a bug, has Probably to do with the white spaces in the SSID name. I’ll try to fix that.
I’ ll check also the board and sail logo. 
I guess that you are on firmware SW5.61 ?

Greetings, Jan.

Verzonden vanuit Mail voor Windows

Van: Rolzzz
Verzonden: maandag 19 december 2022 23:27
Aan: RP6conrad/ESP-GPS-Logger
CC: Subscribed
Onderwerp: [RP6conrad/ESP-GPS-Logger] Config.txt file issues (Issue #12)

Hello there,
Few things I've noticed in the config file - this might be something to do with in built web browser
"cal_speed" always reverts back to "3.6km/h" instead of staying on pre-set, mine is "1.9438 knots"
most annoying one
ssid only keeps first word of ssid - for example my ssid is "Moonbase Alpha 2.4Ghz" but in web browser config it only shows "Moonbase" so when I change a setting and don't re-set this I lose wifi connectivity and have to try to connect via the default AP
Board and Sail logo links in web browser both point board link https://www.seabreeze.com.au/img/photos/windsurfing/19375156.jpg so choosing Severne Sail presents Simmer logo (number 8)

**Comment by Rolzzz** [comment]
Hi Jan,

yes on FW SW5.61

obviously none of these are a show stopper, but thought I'd be helpful with making note of things that I come across.

Cheers!

**Comment by Freezer-SD** [comment]
Would it be possible to have multiple SSID's? Like in the phone, one can store multiple ones. 
Another tip I heard is about OTA updates. Once having wifi, it should be able to check the latest firmware on github and downloading it. Just single button to update it in the web interface would do the trick.

**Comment by RP6conrad** [comment]
There is a new update with bugfixes and  changes.   I all files (ubx, gpx, gpy, sbp) are logged, 5Hz is the advised rate. @10Hz, lost points are possible.
 * SW5.63
* Added GPX file format (log @ 1Hz)
 * Added GPY file format (first draft, but can be read now with last version of gps-speedreader)
 * If no config file : Wifi AP waiting time = 120 s
 * Bugfix config webserver : no switching to km/h if knots was set.
 * Bugfix for SSID with white spaces
 * Added support for BN266 e-paper (still 213 layout !!)
 * Changed GPS-parser union to struct, every ubx message has its own struct now
 * Added ubx nav dop Msg for extracting HDOP
 * Added ubx mon ver Msf for extracting sw / hw version ublox
 * Changed baudrate ublox to 38400, necessary for 10Hz navDOP + navPVT
 * Correction timestamp list files with FTP 
 * Added sail logo "Severne" = 10 (the same as the board logo)
 * Added board logo "F2" = 10
 * Added watchtdog for WAKE UP screen (hangs sometimes after OTA)
 * Added loadbalance for flushfiles()

**Comment by Rolzzz** [comment]
Thanks Jan,

Can we just run ubx and gpy and still keep 10Hz?
Is it if we log all formats that the lost points happen?

As doing testing to get authorisation for GPST eligibility device, my priority is more accuracy with 10Hz over config.txt file issues.

**Comment by RP6conrad** [comment]
With a Sandisk Ultra 16GB card, I had next results : 
@5Hz, ubx, gpy, sbp and gpx logged together with no lost points
@10Hz, ubx, gpy, sbp and gps logged together gives lost points
@10Hz, ubx, gpy and sbp logged together no lost points.

Gpy format is still a draft version, and only gps-speedreader can read them now. There are still some issues with handling lost points, and local time. Peter is working on it. 

For testing purposes, I advice to log ubx and sbp together @10Hz. Best to send out the ubx files for comparison, as these have the highest resolution and the most information in it.
But check always your own files with gps-speedreader (the “Message window” reports lost points) !

In daily “surf live”, I use 5Hz : file size, and less critical for the “acceleration” limit which is used in all sites (GP3S, GPSTMC…)
The most important thing for a good quality signal is however the positioning of the logger : on the head or on your upperarm gives the best reception quality, and thus the lowest sAcc / hDOP values.

Greetings, Jan.

Verzonden vanuit Mail voor Windows

Van: Rolzzz
Verzonden: donderdag 22 december 2022 0:26
Aan: RP6conrad/ESP-GPS-Logger
CC: RP6conrad; Comment
Onderwerp: Re: [RP6conrad/ESP-GPS-Logger] Config.txt file issues (Issue #12)

Thanks Jan,
Can we just run ubx and gpy and still keep 10Hz?
Is it if we log all formats that the lost points happen?
As doing testing to get authorisation for GPST eligibility device, my priority is more accuracy with 10Hz over config.txt file issues.

**Comment by Rolzzz** [comment]
Jan ur a Wizard!
All 3 items were were sorted!

Happily resolve this one!
I really now can't wait to test on the water once my water proof paint arrives.

Merry Christmas to you! 🎄🎅🏻
