### ISSUE TITLE
Support logging using 3 GNSS systems

### ISSUE THREAD

**Issue by prichterich** [RP6conrad/ESP-GPS-Logger#4]
The current firmware version does not set which GNSS systems are used, so the default (GPS + GLONASS) is used. User can pre-configure GPS chips (other than the BN180) to use other systems using u-center, but that requires extra equipment (FTDI cable) and skills (using u-center).

I propose to add config flags to use additional GPS systems, in particular Galileo. The BN220, 280, and 880 chips all can handle 3 systems at 5 Hz without problems, and _probably_ also at 10 Hz (I usually use 5 Hz, but I think decrepit uses 10 Hz with his prototypes).

The general thinking is tracking satellites from 3 systems gives higher accuracy than from 2 systems. The benefits may be small in situations where reception is excellent and 18+ GPS+GLONASS satellites can be tracked, but a reduction in reported error estimates can still be seen.

I have added a config flags and the necessary config sentences in my code, but only for Galileo. I have not checked in the changes to my fork on Github yet because there are still some open questions:
1. What should be the default - 2 or 3 GNSS systems?
2. Should BeiDou also be supported (as an alternative to Galileo)?

Regarding BeiDou: in my tests with different BN chips, I found that they do not all support BeiDou, even if they report the same firmware version (3.0.1). One chip ignores setting BeiDou on completely, another chip seems to accept the setting.  It would be interesting to hear about other chips. I also do not have any data if adding BeiDou improves accuracy.

**Comment by RP6conrad** [comment]
Can you give me the settings in U-center for 3 different GNSS (see prontscreen) ? 
I have several Beitian BN GPS which have still ROM version 2, these do not support Gallileo. 
I prefer to have default 2 GNSS, and configurable 3. I prefer Galileo, but I have no experience with 3 GNSS settings. Maybe with ROM version 2 only Beidou is possible.





Greetings, Jan.
Verzonden vanuit Mail voor Windows

Van: prichterich
Verzonden: zaterdag 14 mei 2022 16:08
Aan: RP6conrad/ESP-GPS-Logger
CC: Subscribed
Onderwerp: [RP6conrad/ESP-GPS-Logger] Support logging using 3 GNSS systems(Issue #4)

The current firmware version does not set which GNSS systems are used, so the default (GPS + GLONASS) is used. User can pre-configure GPS chips (other than the BN180) to use other systems using u-center, but that requires extra equipment (FTDI cable) and skills (using u-center).
I propose to add config flags to use additional GPS systems, in particular Galileo. The BN220, 280, and 880 chips all can handle 3 systems at 5 Hz without problems, and probably also at 10 Hz (I usually use 5 Hz, but I think decrepit uses 10 Hz with his prototypes).
The general thinking is tracking satellites from 3 systems gives higher accuracy than from 2 systems. The benefits may be small in situations where reception is excellent and 18+ GPS+GLONASS satellites can be tracked, but a reduction in reported error estimates can still be seen.
I have added a config flags and the necessary config sentences in my code, but only for Galileo. I have not checked in the changes to my fork on Github yet because there are still some open questions:
1. What should be the default - 2 or 3 GNSS systems?
2. Should BeiDou also be supported (as an alternative to Galileo)?
Regarding BeiDou: in my tests with different BN chips, I found that they do not all support BeiDou, even if they report the same firmware version (3.0.1). One chip ignores setting BeiDou on completely, another chip seems to accept the setting. It would be interesting to hear about other chips. I also do not have any data if adding BeiDou improves accuracy.

**Comment by Jim-Flex** [comment]
Hi Jan,
Is this what you mean?

Originally I had no setting in the config.txt, then I realised I didn’t so put the line "gnss”:3  It didn’t make any difference.

Cheers,
Jim

**Comment by RP6conrad** [comment]
Default is 3 gnss, but there are beitian modules with old firmware, these will only receive 2 gnss. (Ublox rom core 3.01 versus rom core 2.01). Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Flex ***@***.***> Datum: 11/10/22  11:42  (GMT+01:00) Aan: RP6conrad/ESP-GPS-Logger ***@***.***> Cc: RP6conrad ***@***.***>, Comment ***@***.***> Onderwerp: Re: [RP6conrad/ESP-GPS-Logger] Support logging using 3 GNSS systems (Issue #4) 

Hi Jan,

Is this what you mean?



Originally I had no setting in the config.txt, then I realised I didn’t so put the line "gnss”:3  It didn’t make any difference.



Cheers,

Jim

**Comment by RP6conrad** [comment]
Actual SW gives different options for 3 GNSS : GPS + Glonas + Galileo, or GPS + Glonas + Beidou
