### ISSUE TITLE
Support NAV-SAT sentences

### ISSUE THREAD

**Issue by prichterich** [RP6conrad/ESP-GPS-Logger#5]
The current firmware only logs NAV-PVT sentences. But for evaluation and debugging, it can often be useful to also have NAV_SAT sentences to see which satellites where used, and what the signal levels (C/N0) were. For example, I recently ordered two BN220 chips which behaved quite differently. One started slower, and often tracked fewer satellites. Looking at signal levels from NAV_SAT sentences showed that the chip with fewer satellites had an average signal strength that was about 3 db lower.

I propose to add a config flag that allows logging of NAV_SAT sentences. NAV-SAT sentences can be 4 x larger than NAV-PVT sentences when many satelites are tracked, so transmission rates are an issue. This can be partly addressed by logging NAV-SAT only every 10th cycle, which works fine at 5 Hz.  The default should be to not log NAV-SAT sentences, since this information is not normally used to determine speeds.

I have modified the local copy of my fork to support NAV_SAT logging, but not pushed the changes to GitHub for various reasons. If anyone else wants to also use NAV-SAT, please let me know, and I'll put the change up.

**Comment by RP6conrad** [comment]
I did take a look for the NAV_SAT sentences, but as they have a variable length, It seemed not so easy for me. The baud rate is now 19200 baud, which is fine for the NAV_PVT. Is there a setting in the M8N so that the NAV_SAT is ***@***.*** Hz, and the ***@***.*** Hz ? Otherwise, a higher baud rate is necessary.
For the moment, I have no plans for logging the NAV_SAT, but as someone will evaluate three GNSS, it could be usefull/necessary.

Greetings, Jan.

Verzonden vanuit Mail voor Windows

Van: prichterich
Verzonden: zaterdag 14 mei 2022 16:18
Aan: RP6conrad/ESP-GPS-Logger
CC: Subscribed
Onderwerp: [RP6conrad/ESP-GPS-Logger] Support NAV-SAT sentences (Issue #5)

The current firmware only logs NAV-PVT sentences. But for evaluation and debugging, it can often be useful to also have NAV_SAT sentences to see which satellites where used, and what the signal levels (C/N0) were. For example, I recently ordered two BN220 chips which behaved quite differently. One started slower, and often tracked fewer satellites. Looking at signal levels from NAV_SAT sentences showed that the chip with fewer satellites had an average signal strength that was about 3 db lower.
I propose to add a config flag that allows logging of NAV_SAT sentences. NAV-SAT sentences can be 4 x larger than NAV-PVT sentences when many satelites are tracked, so transmission rates are an issue. This can be partly addressed by logging NAV-SAT only every 10th cycle, which works fine at 5 Hz. The default should be to not log NAV-SAT sentences, since this information is not normally used to determine speeds.
I have modified the local copy of my fork to support NAV_SAT logging, but not pushed the changes to GitHub for various reasons. If anyone else wants to also use NAV-SAT, please let me know, and I'll put the change up.

**Comment by RP6conrad** [comment]
Support for NAV_SAT sentences will be in the next update. The rate will be 1/10 of the NAV_PVT rate. It can be set in the configuration. I noticed that GPS-Results cannot handle ubx files correctly with NAV_SAT, as there appear missing points when NAV_SAT msg with the same iTow is in the ubx. Uploading to GP3S will not work with these ubx files !

**Comment by RP6conrad** [comment]
NavSat is supported, can be switched on/off over the settings. Rate is 10% of the Nav Pvt
